### ISSUE TITLE
go-difflib (external module) "NO LONGER MAINTAINED"

### ISSUE THREAD

**Issue by wilson-mar** [cruise-automation/daytona#47]
https://github.com/pmezard/go-difflib (a partial port of Python difflib) has been updated to contain "IS NO LONGER MAINTAINED." It's docs are at: https://pkg.go.dev/github.com/pmezard/go-difflib/difflib?tab=doc

**Comment by broamski** [comment]
Hi @wilson-mar thanks for reporting. This is an indirect dependency via https://github.com/stretchr/testify. If this is still a concern to you, I'd raise an issue on that repository. Thanks for using DAYTONA!
